### ISSUE TITLE
Does it still work with Untiy 2019.3 ?

### ISSUE THREAD

**Issue by roboserg** [marijnz/unity-editor-spotlight#3]
Does it still work with Untiy 2019.3 ?

**Comment by marijnz** [comment]
I haven't tested it. Feel free to and share here.On Apr 6, 2020 16:22, roboserg <notifications@github.com> wrote:
Does it still work with Untiy 2019.3 ?

**Comment by Team-on** [comment]
@roboserg No, spotlight window blinks each frame in 2019.3. But this fork works well https://github.com/edatencio/unity-editor-spotlight .

**Comment by jasursadikov** [comment]
@roboserg Unity has it's own implementation now. Check Unity Quick Search package in package manager.
